### PR TITLE
Nmc/1905 auto upload

### PR DESCRIPTION
**Pull request by surinder-tsys**
- [ ] Tests written, or not not needed

### CODE REVIEW

**Comment by surinder-tsys** [comment]
> What is goal of this PR? Maybe we can then split it and have majority of it upstream?

This PR contains NMC customization changes only and as follows:
1. Changing Auto-Upload folder to Camera-Media from InstantUpload.
2. Folder icon with camera differentiator for Auto-Uploaded folders.

**Comment by tobiasKaminsky** [comment]
This can also be upstreamed, except of "Kamera-Medien" change.
We will then take care of folder icon.
MC tinted one will then be replaced via this PR.

**Comment by surinder-tsys** [comment]
> This can also be upstreamed, except of "Kamera-Medien" change. We will then take care of folder icon. MC tinted one will then be replaced via this PR.

Code has been up-streamed to NC: https://github.com/nextcloud/android/pull/11543

Up-streamed code has been reverted and only the customization code is kept.

**Comment by surinder-tsys** [comment]
Closing the PR as all the changes are merged to NC.

**Pull request closed without merging**
